### PR TITLE
Streamline graph

### PR DESCRIPTION
**Pull request by seabbs**
Adds new streamlined graph. Code also in Nicks repo so may not need here.

### CODE REVIEW

**Comment by seabbs** [comment]
[Uploading rt_sgtf_scatter.pdf…]()

**Comment by seabbs** [comment]
[rt_sgtf_scatter.pdf](https://github.com/epiforecasts/covid19.sgene.utla.rt/files/5817030/rt_sgtf_scatter.pdf)

**Comment by sbfnk** [comment]
Two issues:
1) I wonder if it's clear that they're 5 panels and need to be read in order. I'd be tempted to experiment with `lemon::facet_rep_wrap` (e.g. using `repeat.tick.labels = "all"`)
2) Legend cut off.

**Comment by seabbs** [comment]
[rt_sgtf_scatter.pdf](https://github.com/epiforecasts/covid19.sgene.utla.rt/files/5817116/rt_sgtf_scatter.pdf)


`lemon` is new to me. Like it.

**Pull request closed without merging**
